use [mcbean.clinic]

begin transaction

INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('50', '50% Rx GAP x 5 min, patient tolerated well. No erythema. Neutralized well.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('70', '70% Rx GAP x 5 min, patient tolerated well. No erythema. Neutralized well.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('A', 'Anterior')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('A1', 'Acne Vulgaris mild with open and closed comedones and scattered erythematous papules')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('A2', 'Moderate Acne Vulgaris with open and closed comedones and papules and a few pustules. Treatment Discussion: Diet, Hygiene and cleansers,Topical treatment options, Systemic treatments with Antibiotics and possibly Accutane, Peels,MCD, Genesis,Phototherapy, BCP for females')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('A3', 'Severe Acne with numerous pustules and inflammatory lesions.Marked eythema and scar formation.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('A4', 'Cystic Acne of chest and back with inflammatory nodules,cystic lesions and Hypertrophic scarring.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AA', 'Alopecia Areata')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AAC', 'Anti-aging consultation Discussion topical anti-aging creams,sunscreens,Peels,Microdermabrasions,Botox,Fillers,Laser and Plastic surgery')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AAI', 'Alopecia Areata treated with Kenalog 2.5-5.0 mgm/ml')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ab', 'Abdomen')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Abi', 'Antibiotics')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ac', 'Accutane')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ac1', 'Accutane 10 mg qd, Side effects discussed, Pregnancy contraindicated in women, mood changes, depression,dryness of skin and lips.Blood test monitoring not required for short term treatment.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ac4', 'Accutane 40 mg QD 3-4 months.Adjust dosage higher or lower if indicated.Side effects discussed. Advised re: pregnancy avoidance in females,mood changes dryness etc. Important to read package insert re: all potential side effects. Monitor Cholesterol and Triglycerides')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AcN', 'Acne Neonatorum')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Acu', 'Cutera Xeo Acutip500   J/cm    Pulses X    Cost')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AD', 'Atopic Dermatitis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AE', 'Acne excorie')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AF', 'Angiofibroma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AH', 'Axillary Hyperhidrosis.Patient complains of increased sweating of both ampits which causes social embarassment and soiling of clothing.Treatment options discussed Drysol,Dehydral,Botox  and surgery. Botox   Units/side  Lot  EXP  Cost')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AK', 'Actinic Keratoses of sun exposed areas treated with Cryospray and/or surgitron/Laser excision ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Al', 'Aldara QHS under occlusive drsg with 15% Salicylic Acid in vaseline QAM.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ald', 'Aldara cream to be applied 3-4 X /wk for 3-4 months.Stop treatment for 1-2 wks if the area becomes inflamed.   50mgm/gm #12 #24')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('All', 'Allegra')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Aly', 'Alyria cleanser and astringent')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Am', 'Amevive 15 mgm IM X 12 weeks')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AN', 'Angioma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Anh', 'Antihistamines')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('ANi', 'Acanthosis Nigricans')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('15', 'RXGAPX 15 @    mins Cost $ patient tolerated well.  No erythema.  Patient tolerated well. ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ant', 'Anthelios 60')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ap', 'Apocrine Hidrocystoma eyelid')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AQ', 'Aldara QOHS & titrate to pinkness x 3m.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AR', 'Acne Rosacea')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Arc', 'Aristocort C cream 0.5% Triamcinolone 15 gm Valeo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Arr', 'Aristocort R 0.1% cream TID 30 gm 500 gm Valeo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Art', 'Arthritis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('AS', 'Acne sugery')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('ASc', 'Facial Acne scarring')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Asy', 'asymptomatic')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('At', 'Atarax 25 mgm Qhs prn')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ax', 'Axilla')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Az', 'Azothiaprine (Imuran)')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('B', 'Biopsy')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ba', 'Bactroban Cream TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BAC', 'Bactrim DS BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Bal', 'Balanitis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BC', 'Basal Cell Carcinoma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Bds', 'Bactrim DS BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Be', 'Betamethasone cream 0.1% QID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ben', 'Benadryl 50 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Bet', 'Betacaine topical gel Apply Q 5 minutes for 45 min. prior to procedure')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Bi', 'Bilateral')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BIA', 'Biacna Tretinoin 0.025% Clindamycin 1.2%  Valeant')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Bl', 'Blepharitis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ble', 'Blepharoplasty')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BMS', 'Burning Mouth Syndrome')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BN', 'Blue Nevus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Bo', 'Botox (ona) Allergan DIN 01981501 100 units/vial   Units   Lot   Exp  Cost')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BP', 'Bullous Pemphigoid')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Br', 'Brow lift bilateral')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BRC', 'Biopsy results called to patient')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Bss', 'Burning scrotum syndrome')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BT', 'Blood tests normal')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BTS', 'Burning Tonque Syndrome')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Bu', 'Buttock')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('BXO', 'Balanitis Xerotica Obliterans')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('C', 'Corns treated with CRY-AC-3 cryosurgical device followed by laser vaporization with the Luxar-20 CO2 using 1.8mm spot size, continuous pulse and 3-4 watts power setting. ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CA', 'Condyloma Acuminata treated with CRY-AC-3 cryosurgical device using limited 30-40 second freeze-thaw cycles to lesions.  ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CAL', 'Calcifying Epithelioma of Malherbe')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Cc', 'Cryotherapy to Acne Cysts')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CD', 'Contact Dermatitis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ce', 'CeraVe')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CF', 'Cosmetic follow-up left message')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CH', 'Cutaneous Horn treated by excision and biopsy')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CHN', 'Congenital Hairy Nevus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CI', 'Acne cysts injected with Kenalog 2.5 mgm/ml')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Cl', 'Clindoxyl gel QD. Apply sparingly')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Cll', 'Clobex Lotion 0.05% BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CLR', 'Cosmetic Laser Removal with Luxar 20  2-4 watts fluence .8mm spot size')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CLS', 'Clobex (Clobetasol 0.05%) spray BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CM', 'Corynebacterium')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('CN', 'Chondrodermatitis Nodularis Helicus of ear')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Co', 'Continue')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Con', 'Consent signed by patient or guardian')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Cos', 'Cosmetic procedure not covered by Alberta Health')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Cs', 'Cyclosporin')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Cy', 'Cyclocort cream QID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Cyl', 'Cyclocort lotion BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('D', 'Dsyhidrosis with multiple vesicular and eczematous lesions ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('D3', 'Diane 35 Cyproproterone 2 mgm E.Estradiol 0.035 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dap', 'Dapsone 100 mgm QD Try to reduce to lowest dosage')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Db', 'Dermabase')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dc', 'Decrease')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('De', 'Dermalive')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DF', 'Dermatofibroma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DG', 'Dermographism')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DH', 'Dermatitis Herpetiformis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Di', 'Diprosalic ointment TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dif', 'Differin Adapalene cream/gel 0.1%')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dil', 'Diprosalic lotion BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dix', 'Differin XP Adapalene gel 0.3%')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DLE', 'Discoid Lupus Erythematosus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DMC', 'Dystrophia Mediana Canaliformis thumb')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DN', 'This patient has multiple Nevi of the body.The lesions all vary in size,shape and color and are Dysplastic Nevi.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Do', 'Dovonex oint BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dob', 'Dovobet Ointment BID 50ug/g Calcipotriol 0.5% Betametasone 60g 120g')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dol', 'Dovonex lotion BID to scalp')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DoP', 'Delusions of Parasitosis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dox', 'Doxycycline 100 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DP', 'Surgitron excision multiple lesions of Dermatosis Papulosa Nigra and Seborrheic Keratoses of the face.Patient cautioned re: Hyperpigmentation')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DS', 'Derma-Smoothe/FS Fluocinolone Acetonide 0.01% In Topical refined Peanut oil')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('DSA', 'Desseminated Superficial Actinic Porokeratosis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dv', 'Dermovate (Clobetasol)  BID 15 gm 50 gm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dx', 'Dermatix gel applied QHS for scar lightening')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dz', 'Aczone 5% Dapsone Valeant')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('E', 'Excision')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Eac', 'Erythema Annulare Centrifugum')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EB', 'Excision and Biopsy surgitron/laser vaporization to base of the lesion ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EBL', 'Excision, Biopsy and Laser vaporization to the base of the lesion')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EBN', 'Excision and Biopsy Nevi')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ec', 'Eczema')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ecc', 'Ecchymoses')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('ED', 'Erythroderma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ef', 'Efudex BID under occlusive drsg.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EH', 'Eczema Herpeticum')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EIB', 'Erosio Interdigitalis Blastomycetica')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EIN', 'Excision irritated Nevi')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('El', 'Elocom cream BID 15,50 gm Schering')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Eli', 'Elidel cream BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EM', 'Erythema Multiforme')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Emo', '2.5% Emocort cream TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EN', 'Excision irritated Nevi')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Enb', 'Enbrel 50 mgm Subcutaneous BIW')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('ENO', 'Erythema Nodosum lower legs')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ep', 'Epuris Cipher Isotretinoin')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EPI', 'Epidermal Nevus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Er', 'Erythematous')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ery', 'Erythromycin 250 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EV', 'Epidermodysplasia Verruciformis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('EW', 'Elbow Warts treated with CRY-AC-3 cryosurgical device followed by laser vaporization with the Luxar-20 CO2 using 1.8mm spot size, continuous pulse and 3-4 watts power setting. ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ex', 'Excoriations')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ey', 'Eyelid')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Eyb', 'Eyebrow')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('F', 'Forehead')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Fa', 'Famvir 500 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FB', 'Folliculitis Barbe of beard area with ingrowing hairs and infected hair follicles')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FD', 'Folliculitis Decalvans of scalp with pustule formation and scarring Alopecia')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FDE', 'Fixed Drug Eruption')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FEE', 'Multiple Fibroepithelial polyps of upper and lower eyelids bilaterally treated by excision')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FEP', 'Multiple Fibroepithelial Polyps treated by excision')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FH', 'Family History')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Fib', 'Fibromyalgia')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FK', 'Folliculitis Keloidalis Nuchae')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Fn', 'Fucidin cream BID to affected areas')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Fnh', 'Fucidin H BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FO', 'Forearm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Fol', 'Folliculitis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FP', 'Female pattern Alopecia')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FR', 'None')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FS', 'Fordyce Spots')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FU', 'Follow up visit')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Fuh', 'Fucidin H BID ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('FW', 'Face Warts treated with CRY-AC-3 cryosurgical device using limited 30-40 second freeze-thaw cycles to lesions.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('G', 'Glabella')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GA', 'Granuloma Annulare')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Gan', 'Ganglion')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GD', 'Grovers Disease')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ge', 'Laser Genesis treatments')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GEN', 'Laser Genesis treatment using Coolglide XEO  Fluence j/cm2  13-14, Spot size 5 mm,  Pulse width 0.3ms, Pulses X     Area treated           Cost ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GF', 'Granuloma Faciale')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Gn', 'Glyquin Qhs')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GO', 'Gorilla tape prn.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GP', 'Generalized pruritus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GPs', 'Guttate Psoriasis with widespread papulosquamous lesions ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GR', 'Granuloma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GT', 'Geographic Tongue')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('GW', 'Genital Warts treated with CRY-AC-3 cryosurgical device followed by laser vaporization with the Luxar-20 CO2 using 1.8mm spot size, continuous pulse and 2-3 watts power setting. ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('H', 'Hypertrophic')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HAK', 'Removal numerous Hypertrophic Actinic Keratoses of sun exposed areas by surgitron/laser excision and cryospray')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HC', '1% Hydrocortisone cream TID to affected areas')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HE', 'Hemangioma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HEP', 'Hepatitis C')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HFM', 'Hand Foot and Mouth Disease')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Hi', 'Hirsuitism')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HL', 'Patient complains of diffuse hair loss for an extended period of time.A review of systems is non contributory and health has been relatively stable.No recent febrile illness or major medical or surgical problems.Clinical examination reveals diffuse hair loss and no evidence of inflammation. Treatment Rogaine BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HN', 'Halo Nevi')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HOP', 'Hypopigmentation')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HP', 'Herpes Progenitalis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HPO', 'Hypopigmentation')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HPP', 'Hyperpigmentation ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HS', 'Hidradenitis Suppurativa')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HSV', 'Herpes Simplex')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HU', 'Progress Enrollment HUMIRA Pen 80 mgm SC week 0 40 mgm SC Q2wks begining wk 1')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HW', 'Hand Warts treated with CRY-AC-3 cryosurgical device followed by laser vaporization with the Luxar-20 CO2 using 1.8mm spot size, continuous pulse and 3-4 watts power setting. ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Hy', 'Hydroval cream BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Hyd', 'Hydrosal Gel Al Cl Hexahydrate 15% prn Valeo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HYE', 'Hyperkeratotic eczema vs Psoriasis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HYP', 'Hyperhidrosis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('HZ', 'Herpes Zoster')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('I', 'Inferior')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('IB', 'Insect bites')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ic', 'Increase')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ich', 'Ichthyosis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('IE', 'Primary irritant eczema of the hands aggravated by exposure to chemicals,detergents,solvents and hot water.Use vinyl gloves and avoid irritants')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('im', 'improving')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('IN', 'Intertrigo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ind', 'induration')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('IPL', 'Intense Pulse Light treatment using Coolglide XEO with LP560 handpiece. Fluence  j/cm2 13-14  Pulse width 0.3 msec   Pulses X      Cost $')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ir', 'Irritated')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('JI', 'Jessner''s Infiltrate')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('JJ', 'J & J Liquid Bandaide')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('JUP', 'Juvederm Ultra Plus with Lidocaine 0.8 ml X  Syringes  LOT      REF    Consent signed Side effects discussed   Cost')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('JXG', 'Juvenile Xanthogranuloma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('K', 'Kenalog injections 2.5 mg/ml ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('KA', 'Keratoacanthoma vs Squamous Cell Carcinoma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ke', 'Indurated thickened Keloid scars injected with Kenalog 5-10 mg/ml')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('KN', 'Keloidalis Nuchae')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('KO', 'KOH and Culture for fungi')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('KP', 'The patient has multiple keratotic papules of the upper arms typical of Keratosis Pilaris')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('KPS', 'Keratolysis Plantare Sulcatum')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Kw', 'Kwellada P lotion.Apply and leave on for 8 hrs 2 days in a row.Wait 1 week and reapply.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('L', 'Liquid nitrogen spray ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('La', 'Lamisil 250 mgm QD X')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Lac', 'Lamisil cream BID 15 gm 30 gm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LE', 'Lentigenes')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LEN', 'Multiple Lentigenes of sun exposed areas treated with cryospray')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Lev', 'Levulan-IPL')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LHR', 'Laser Hair Removal using Coolglide XEO NDYAG 1064  Fluence J/cm    Pulse width 20 ms  Spot size 10mm. No of Pulses X     Cost $      Patient tolerated well, No erythema or swelling. Follow up in 6 weeks.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LI', 'Lipoma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Lic', 'lichenification')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LMC', 'Appointment cancelled leaving insufficient time to fill it with another patient')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LMM', 'Lentigo Maligna Melanoma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LN', 'Liquid nitrogen to for treatment of acne.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Lo', 'Lotriderm cream TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LP', 'Lichen Planus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LRE', 'Livedo Reticularis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LSA', 'Lichen Sclerosis et Atrophicus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LSC', 'Lichen Simplex Chronicus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LT', 'Laser Treatment')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LU', 'Lupus Erythematosus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LUK', 'Leukoderma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ly', 'Lymph node')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('M', 'Multiple')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('M1', 'Minocin 100 mgm BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('M5', 'Minocin 50 mgm BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MA', 'Medical Assessment')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('mac', 'maculopapular')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MC', 'Molluscum Contagiosum treated with CRY-AC-3 cryosurgical device using limited 30-40 second freeze-thaw cycles to lesions.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MD', 'Microdermabrasion using diamond tipped wand with suction to face, eye, neck. Mask. Patient tolerated well.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MDC', 'Coarse face, eye, neck micro. mask')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MDF', 'Fine tip face eye neck micro mask')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MDM', 'Medium tip face, eye, neck micro. mask')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MDX', 'XCoarse face, eye, neck micro. mask.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Me', 'Metrocream 0.75% BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Meg', 'Metrogel 0.75% or 1% BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Mel', 'Melanotic Macule of lower lip')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MF', 'Mycosis Fungoides')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MH', 'Migraine Headaches')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('ML', 'Meilolabial Folds')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MM', 'Malignant Melanoma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MN', 'Patient has multiple Nevi which appear stable.Clinical examination does not reveal any evidence of cancerous change.A biopsy is not indicated at this time.The patient was advised to check weekly using a full length mirror for any rapid change in size,shape or color of any moles.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Mo', 'Moisturisers')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Mor', 'Morphea')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MP', 'Male pattern Alopecia as evidenced by thinning hair of the androgenetic areas of the scalp.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MR', 'Moisturisers')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Mtx', 'Methotrexate 2.5 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('MU', 'Mucoid Cyst distal IP joint treated by incision and drainage')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Mum', 'Mucoid Cyst of the buccal mucosa treated by incision and drainage')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('N', 'Nevus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NA', 'NAD. FU prn.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NB', 'Bilateral Infraorbital Nerve block 1% Xylocaine')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NC', 'No charge')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('ND', 'Nail Dystrophy')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NE', 'Neurotic excoriations with numerous pick like lesions and scarred areas ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ner', 'Nerisone Cream TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NF', 'Neurofibroma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ni', 'Nevi')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Nic', 'Nizoral Cream BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Nis', 'Nizoral shampoo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Niz', 'Nizoral 200 mgm Qd X 15 days.Then Q wk X 10')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NL', 'Nasolabial folds bilateral')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NLD', 'Necrobiosis Lipoidica Diabeticorum')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NLS', 'Nevus Lipomatosus Superficialis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NN', 'Non Cancerous No Treatment required')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('No', 'Appointment search results reveal a no-show @ Hogwarts which is unlikely an office error')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NOD', 'Nodules')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Nor', 'Noritate cream BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NOS', 'No show ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NP', 'Notalgia Paresthetica')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NR', 'No recurrance previously removed skin cancer')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NS', 'Non specific')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NSN', 'GIVEN NO SHOW NOTICE BY DR. HOGBEN')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('NT', 'No treatment required')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Num', 'Nummular Eczema')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('nw', 'Knee Warts treated with CRY-AC-3 cryosurgical device followed by laser vaporization with the Luxar-20 CO2 using 1.8mm spot size, continuous pulse and 3-4 watts power setting.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('On', 'Onychodystrophy')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('OnG', 'Onychogryphosis great toenail')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Onl', 'Onycholysis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ox', 'Oxsoralen 10 mgm Take 2 pills 1 hr.prior to UVA')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('P', 'Posterior')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PA', 'Pityriasis Alba ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pap', 'Papular Eczema')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Par', 'Paronychia')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PaS', 'Papulosquamous')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PC', 'Poikiloderma of Civatte')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PCT', 'Porphyria Cutanea Tarda')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PD', 'Perioral Dermatitis with multiple eythematous papules in a circumoral distribution.Treatment Tetracycline 250 mgm TID X 3 wks then BID X 3 wks. ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pe', 'Penlac QD to nails')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Per', 'Perioral')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PG', 'Pyogenic Granuloma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PHH', 'Palmar Hyperhidrosis Treatment options Dehydral Hydrosal Botox injections')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PHN', 'Post Herpetic Neuralgia')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PLC', 'Pityriasis Lichenoides Chronica')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PM', 'Polymorphous light eruption sun exposed areas')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PN', 'Prurigo Nodularis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PO', 'Peri-orbital areas bilateral')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('POD', 'Refer to Podiatrist')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pol', 'Polysporin cream BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pp', 'Propecia 1 mgm QD')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PPD', 'Pigmented Purpuric Dermatosis lower legs bilaterally')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PPH', 'Palmo-Plantar Hyperhidrosis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PPK', 'PalmoPlantar Keratoderma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PPs', 'Pustular Psoriasis hands and feet')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PR', 'Pityriasis Rosea')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Prc', 'Propecia 1mgm QD')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pre', 'Prednisone')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Prl', 'Perleche at the angles of the mouth. Treatment Lotriderm cream TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pro', 'Protopic ointment 0.1% BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PRP', 'Pityriasis Rubra Pilaris')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pru', 'Pruritus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PRW', 'Cutera Prowave 770  J/CM2       A  B  C    No of pulses      Area treated          Cost')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ps', 'Psoriasis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PsA', 'Psoriatic Arthritis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pse', 'Psoriasis Evaluation:   Duration   Family Hx   Nails   Scalp   BSA   PASI   DLQI   Weight      Previous Rx Arthritis   Comorbidities')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LPP', 'This patient has a possible Contact Eczema.Referral to Dr.Laurie Parsons for patch testing')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PU', 'Papular Urticaria')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('pum', 'Pumpkin peel full face X 5 min')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PUP', 'Pruritic urticarial papules of pregnancy')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pur', 'Purpura')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PV', 'Periungual Verruca')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PW', 'Plantar Warts treated with CRY-AC-3 cryosurgical device followed by laser vaporization with the Luxar-20 CO2 using 1.8mm spot size, continuous pulse and 3-4 watts power setting.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Px', 'Prevex cream PRN')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pxb', 'Prevex-B cream TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ra', 'Raptiva 0.7mgm/kg increasing to 1 mgm/kg weekly subcutaneous injection 125 mgm /vial')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RAD', 'Radiesse Merz Implant 0.8 cc 1.5 cc  REF     LOT')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Rc', 'Recurrent')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RD', 'Raynaud''s Disease')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Re', 'Resolving')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Rec', 'Recurrance')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Res', 'Restylane')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RH', 'Referral from Dr. R. Hogben to Dr. A. Behm - Please see chart for Referral Note')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RHK', 'Refer to Dr.Habib A Kurwa for Mohs Surgery')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RLP', 'Refer patient to Dr.Laurie Parsons for patch testing for Contact Dermatitis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RM', 'Refer to Dr.J.Arlette for Mohs Surgery')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ro', 'Rogaine BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('ROS', 'Review of Systems Non Contributory')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RP', 'Refer patient to Plastic Surgeon')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RPo', 'Refer to Podiatrist')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RR', 'Refer Dr.Regine Mydlarski')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RS', 'Refer to Surgeon for excision')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('RT', 'Remnants. FU prn.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('S', 'Surgitron excision')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SA', 'Patient complains of ongoing hair loss.Examination reveals scarring Alopecia.Dx Pseudopelade vs Lichen Planopilaris')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SBC', 'Superficial Multicentric Basal Cell Carcinoma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SC', 'Sebaceous Cyst')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SCA', 'Scabies')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SCC', 'Squamous Cell Carcinoma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SCL', 'Sclerotherapy with Sclerodex to multiple superficial veins')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SCU', 'Sculptra reconstituted with 5 ml sterile water and 1ml 1% Xylocaine Lot  Exp    No. Vials   Cost     Consent signed and procedure discussed ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SD', 'Striae Distensae')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SE', 'Side effects discussed')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SEB', 'Seborrheic Dermatitis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SEc', 'Stasis Eczema lower legs')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SH', 'Nodules of Sebaceous hyperplasia')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SHO', 'Shoulder')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Sil', 'Silkis Calcitrol ointment 3 mcg/g  60 Gm Galderma ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SJ', 'Referral from Dr. S Jansen to Dr. A.R. Behm. Please see chart notes for Referral details ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SK', 'Multiple irritated Seborrheic Keratoses and Lentigenes removed by surgitron/laser excision and cryospray')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SM', 'Steatocystoma Multiplex')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SN', 'Nevus Sebaceous')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SO', 'Soluver Plus BID.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SP', 'Stop picking otherwise lesions will not improve')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SQ', 'Sol+/od.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SR', 'Sulfacet R')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('St', 'Stieprox shampoo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ste', 'BioAdvance Enrollment Program Stelara Ustekinumab  45 mgm, 4 wks later 45 mgm, Then 45 mgm Q 12 wks')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Sti', 'Stieva-A cream')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Stm', 'Stievamycin gel 0.025% Tretinoin, 4% Erythromycin')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Su', 'Superior')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SY', 'Multiple Syringomas of eyelids upper and lower bilateral treated by surgitron excision')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('T', 'Telangiectasia')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ta', 'TACTUPUMP Adapalene 0.1% Benzoyl Peroxide 2.5%')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Tac', 'Tazorac cream 0.05% 0.1%')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Tag', 'Tazorac gel 0.05% 0.1%')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TC', 'Tinea Corporis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TCA', 'Trichloracetic Acid Peel')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TCR', 'Tinea Cruris')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Te', 'Tetracycline 250 mg')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ter', 'Tersaseptic cleanser')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TI', 'Tinea Interdigitale web spaces between 4Th and 5Th toes Rx Lamisil cream TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TiV', 'Cutera Titan V    Fluence J/cm2    s        No of pulses      Area treated      Cost')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TM', 'Tinea Manum')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('To', 'Topicort gel TID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Toc', 'Toctino 30 mgm Alitretinoin')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TP', 'Tinea Pedis')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TR', 'Treatment')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Tri', 'Cholesterol and Triglycerides')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TS', 'Topical Steroids')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TU', 'Tinea Ungium')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TV', 'Tinea Versicolor')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TW', 'Tolerated well, no adverse reactions. will increase strength')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('TXL', 'Cutera Xeo Titan XL   Fluence J/CM2      No of pulses        Area treated      Cost')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('U', 'Umbilicus')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('UA', 'Ultraviolet A')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('UB', 'Ultraviolet B')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ul', 'Ultravate cream BID 50 gm Valeant')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('UP', 'Urticaria Pigmentosa')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ur', 'Urticaria: Patient complains of intermittent wheals which come and go.No known allergens Review of systems non contributory.No new medications.Feels well otherwise. Treatment Betaderm 0.1% cream QID Antihistamines')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('V', 'Verruca')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Va', 'Valtrex 500 mgm ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Val', 'Valisone lotion Betamethasone 0.1% 75 ml Valeo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Van', 'Vaniqa cream (Eflornithine HCL 13.9%) BID for Hirsuitism')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('VAS', 'Telangectasia treatment using Coolglide XEO 1064 NDYAG handpiece. Fluence 135 J/Cm2 , Pulse width ms 20, Spot size 5 mm, Pulses X    Area treated    Cost $           Patient warned about side effects such as swelling,bruising and scarring')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ve', 'Vesicular erythematous')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ved', 'Verdeso Desonide 0.05% foam BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('VG', 'Valisone-G cream TID 30 Gm Valeo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Vi', 'Vitiligo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Vit', 'Vitamin A acid cream 0.05%')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('VL', 'Venous Lake')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('VP', 'Verruca Plana')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('VR', 'Von Recklinghausen''s Disease with multiple Neurofibromas and axillary freckling')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('VV', 'Varicose Veins of legs small to medium diameter. ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Vy', 'Vyloma QHS x 8w - titrate decrease if xs rxn.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('W', 'Widespread')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Wa', 'Warned of NS''s.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('We', 'Westcort cream BID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('WEM', 'Widespread erythematous maculopapular symmetrical eruption')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('WR', 'Warts treated with CRY-AC-3 cryosurgical device followed by laser vaporization with the Luxar-20 CO2 using 1.8mm spot size, continuous pulse and 3-4 watts power setting.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('WS', 'Time:  Mth''s  Yr''s  Number:  Size:  Site(s):  Foot:  Treatments:  OTC:   OTC Cryo:   LN2:   Laser:   Bleo.:   Cantharidin:   Rx:   Other:')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('X', 'Xanthoma')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Xa', 'Xamiol Gel BID LEO Calcipotriol 50 mcg Betamethasone 0.50 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('XE', 'Xerosis Eczema')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Y', 'Cutera Xeo 1064 NDYag Laser Treatment  Fluence J/cm2      Pulse width msec     Spot size      No of Pulses X     Cost $')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ya', 'Yasmin BCP Drospirenone 3 mgm Ethinyl Estradiol 0.030 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Z', 'Zovirax 200 mgm')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Zc', 'Zovirax Cream QID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Zo', 'Zovirax ointment QID')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Zy', 'Zyclara cream Qhs X 2 wks D/C X 2wks Repeat cycle X 3   #28')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Wp', 'Wartpeel QHS with an occlusive dressing.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PY', 'Pyratine XR Valeo')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('JXC', 'Juvederm Ultra XC 24mg/ml 0.3% Lidocaine 1.0 mL  LOT  REF')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('PT', 'Refer to Dr. Patricia Ting. See chart for Referral Notes.')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ov', 'Ovita HV 1.0 ml  25mg/ml Hyaluronic Acid')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ver', 'Veralac Valeo Chitosan Horsetail extract Methylsulfonylmethane')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('App', 'Apprilon 40 mg QD Galderma 10mg delay release')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Dy', 'Dysport (Abo) Medicis  DIN 02387735 300 Units/vial  LOT   EXP   1.2 ML  2.5 UNITS/0.1 ML 2.5 units  equal 1 unit Botox')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('XER', 'XERESE Acyclovir 5% HC 1% Valeant')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('OL', 'Olux-E Clobetasol foam 0.05% Stiefel')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Lx', 'Luxiq Foam Betamethasone .12% BID Stiefel')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Pi', 'Picato Ingenol mebutate gel 0.015% for face and scalp X 3 applications 0.05% X 2 Days for arms hands')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ret', 'Retin-A MICRO  Tretinoin 0.1% or 0.04% ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('SAL', '30%  1 coat, patient tolerated well. No erythema.  Cost $ ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('20', 'RXGAPX Gly 20@  Cost $      Patient tolerated well. Peeling expected. ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('30', 'RXGAPX gly30 @   Cost $     Patient tolerated well. No erythema.  ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Onr', 'Onreltea Brimonidine Gel 0.33% QD')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Xo', 'Xolair Omalizumab Novartis 150 mg 300 mg')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('Ju', 'JUBLIA 10% Efinaconazole ')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('XEO', 'Xeomin 100 units/vial')
INSERT INTO ShortCutCode (Code,ReplaceText) VALUES ('LR', 'Luxar CO2 Laser Treatment 2-4 watts')


commit transaction

select * from shortcutcode

